### PR TITLE
Migrate from Material.Angular to Bootstrap

### LINKED ISSUE #26: Move from Angular.Material to Bootstrap
Any comments on this? I think it is worth it to move over to bootstrap as it more 'familiar' to most of us and also there is a lot of examples and support for bootstrap.

### PR DESCRIPTION
**Pull request by egeldenhuys**
Closes #26 

The bootstrap branch does not share a code base with develop, so all files will be replaced with the bootstrap branch. The orphan branch will be merged into develop to keep commit history.

@CDuPlooy is in charge of this PR.

### CODE REVIEW

**Comment by CDuPlooy** [comment]
Thank you Evert!

**Comment by egeldenhuys** [comment]
It is discouraging that the view is blank, then again we the draft screen designs (#45)  are very different to what is currently in develop

**Review by FJMentz — APPROVED** [review]
Very nice. 🤘

**Review by annamarieHelberg — APPROVED** [review]

**Comment by egeldenhuys** [comment]
Note that this PR has deleted the LICENSE file.

**Pull request merged**
