### PR TITLE
Navbar revamp #65

### PR DESCRIPTION
**Pull request by FJMentz**
I cleared items from the navbar so that we can add them as we make the pages it actually points to.

Will also look at the user's name as soon as the authentication is in place.

Please leave any comments. 🗡

### CODE REVIEW

**Review by CDuPlooy — APPROVED** [review]
Try not to swap the order of things in the imports or provides statements, sometimes it will break things. 

Thank you though

**Comment by FJMentz** [comment]
@CDuPlooy, Is there an example of where I did this? Just want to know for future reference. :D

**Review by annamarieHelberg — APPROVED** [review]
I like the style a lot! We can update it later when we have an idea of all of the functionality / pages we would like to view

**Review by egeldenhuys — APPROVED** [review]
Layout looks good, colour scheme looks good.

We might decrease the width of the sidebar once we have all the menu items.

**Pull request merged**
