### PR TITLE
Networks

### PR DESCRIPTION
**Pull request by CDuPlooy**

### CODE REVIEW

**Review by egeldenhuys — APPROVED** [review]
Great stuff!

**Review by FJMentz — APPROVED** [review]
Love the new Interfaces ❤️

**Comment by egeldenhuys** [comment]
@CDuPlooy , There are now merge conflicts after merging other PRs

EDIT: Branches are no longer required to be up to date with develop. This caused major slow down when trying to merge PRs in series

**Comment by CDuPlooy** [comment]
Thanks @egeldenhuys , I wasn't supposed to push those changes xD I fixed it.

**Review by annamarieHelberg — APPROVED** [review]
Hopefully everything works

**Pull request merged**
