### PR TITLE
Graphs

### PR DESCRIPTION
**Pull request by annamarieHelberg**
The skeleton code graphs. We still need to decide on what information to be displayed #75

### CODE REVIEW

**Comment by egeldenhuys** [comment]
A fix for the failing Docker Hub images is in the branch [graphs-docker-hub](https://github.com/TripleParity/docks-ui/compare/graphs...graphs-docker-hub)

**Comment by CDuPlooy** [comment]
For some reason `ng test` is not starting chrome correctly as it isn't capturing any output.

**Comment by egeldenhuys** [comment]
> For some reason `ng test` is not starting chrome correctly as it isn't capturing any output.

@CDuPlooy , this was due to a cache error.

Please trigger the Docker Cloud build with a commit that makes the following change in `.travis.yml`
```
- ng build --prod --aot
```
>
```
- ng build --prod --no-progress
```

According to the [wiki](https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds) `--prod` includes the `--aot` flag.
`--no-progress` because it is not useful to see the garbled output in Travis.

Also note that the `package-lock.json` file will still be tracked until it is deleted and committed.

**Comment by CDuPlooy** [comment]
@egeldenhuys for future reference how did you figure that out?

**Comment by egeldenhuys** [comment]
I branched from your commit and the build passed. Travis starts a new cache when you create a new branch.

**Review by CDuPlooy — COMMENTED** [review]
Thank you @annamarieHelberg !

**Review by CDuPlooy — APPROVED** [review]

**Review by FJMentz — APPROVED** [review]
I'm Happy with this 😄

**Review by egeldenhuys — APPROVED** [review]
Appears to be much more than just graph skeleton code :wink: 

Good work!

**Pull request merged**
