### PR TITLE
User management

### LINKED ISSUE #115: User Management
Permissions and roles will be added later

- [x] View list of users
- [x] Create user
- [x] Update user (change password)
- [x] Delete user

Related back-end PR: TripleParity/docks-api/pull/51

### PR DESCRIPTION
**Pull request by egeldenhuys**
### Added
- User management section to Create, View, Update and Delete users (Closes #115 )

----

TODO:
- [X] View users in datatable
- [X] Create user
- [X] Change password
- [X] Delete user
- [x] Use pages for datatable
- [x] Apply filter to datatable

<details><summary>Screenshots</summary>

screen shot 2018-07-01 at 21 38 14
screen shot 2018-07-01 at 21 38 22
screen shot 2018-07-01 at 21 38 37
screen shot 2018-07-01 at 21 38 53
screen shot 2018-07-01 at 21 39 05
screen shot 2018-07-01 at 21 39 26
screen shot 2018-07-01 at 21 39 32
screen shot 2018-07-01 at 21 39 39
screen shot 2018-07-01 at 21 39 44

</details>

### CODE REVIEW

**Comment by egeldenhuys** [comment]
The user list can now be filtered and displays a maximum of 10 users per page.

screen shot 2018-07-09 at 13 47 32

**Comment by egeldenhuys** [comment]
This PR is now ready to be reviewed. It requires the `tripleparity/docks-api:branch-user-management-_28` image of docks-api.

One way to prevent the UI from using the wrong API version is to expose the API version from docks-api and now allow the user to login if there is a misconfiguration. While some features might still be usable their behaviour may be undefined which will be dangerous. To invalidate active sessions the JWT secret key can be regenerated when the back-end is updated.

**Review by ghost — APPROVED** [review]
The table should maybe be centred but other than that will simplify a lot of other table ideas thanks @egeldenhuys

**Comment by egeldenhuys** [comment]
Waiting for #121 to see how to restructure the directories

**Pull request merged**
