### PR TITLE
[Example] Copy to Clipboard

### PR DESCRIPTION
**Pull request by FJMentz**
Yeah so this isn't anything great, just added the package ts-clipboard that allows you to copy to the clipboard. The main idea for this is to copy logs to clipboard (to avoid downloading a log).

You can find an example in task-card-view.

That's it.

EDIT: Using ngx-clipboard now. Please see latest commit for example.

### CODE REVIEW

**Comment by egeldenhuys** [comment]
We will keep the PR around as an example, thank you

**Comment by egeldenhuys** [comment]
I forgot we still have the card views, so we can actually merge this.
On my system it only copies the first `` character?

**Comment by FJMentz** [comment]
I believe this is due to weird character encodings. I will try to find another way to fix copy that hopefully works on a larger number of encodings, otherwise (since it's not such an important feature) we can let it slide XD

**Comment by FJMentz** [comment]
@egeldenhuys, Can I please ask you to test this again with your funcky stacks XD

**Review by egeldenhuys — COMMENTED** [review]
It works on Chrome, but not Firefox

**Comment by FJMentz** [comment]
Weird observation because it works on both on my side...

**Comment by CDuPlooy** [comment]
Doesn't seem to work in firefox 62; Works in latest chrome builds.

Perhaps open an issue [here](https://github.com/gforceg/ts-clipboard/issues).

**Comment by FJMentz** [comment]
Worked on my latest firefox (62) and latest chrome... Will look into it at a later stage.

Also its no longer ts-clipboard, as per edit we are now using ngx-clipboard. :)

**Comment by CDuPlooy** [comment]
Perhaps we could just do this ourselves following the [Mozilla Guidelines](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard)

**Comment by FJMentz** [comment]
Closing this due to not needing as of yet and also it not working correctly.

**Pull request closed without merging**
