### PR TITLE
Added the logos to assets

### PR DESCRIPTION
**Pull request by FJMentz**

### CODE REVIEW

**Comment by CDuPlooy** [comment]
Remember the favicon 🥇

**Comment by FJMentz** [comment]
@CDuPlooy funny thing with that, as soon as I apply it to the favicon, it stretches it for some reason... will look into this.

**Comment by FJMentz** [comment]
@Paulo-W, can you maybe help with this?

**Comment by FJMentz** [comment]
Found the problem, they aren't square... Will fix that now

**Comment by CDuPlooy** [comment]
Thanks @FJMentz !

**Comment by FJMentz** [comment]
Logos where made square and added the favicon. @CDuPlooy

**Review by egeldenhuys — APPROVED** [review]
Looking professional

**Review by CDuPlooy — APPROVED** [review]
Thanks!

**Review by ghost — APPROVED** [review]
Logo Looks a bit small for now its fine.

**Pull request merged**
