### PR TITLE
Services2

### PR DESCRIPTION
**Pull request by CDuPlooy**
Modified services by changing classes to interfaces.

Also made a few changes to one or two of the API calls.

### CODE REVIEW

**Review by annamarieHelberg — APPROVED** [review]
Looks good!

**Review by ghost — APPROVED** [review]

**Review by FJMentz — CHANGES_REQUESTED** [review]
You're trying to merge into master? Can we please change this to develop XD

**Review by egeldenhuys — CHANGES_REQUESTED** [review]
Please merge from feature branch into develop.

**Comment by CDuPlooy** [comment]
Whoops must have miss clicked, hold on

**Comment by CDuPlooy** [comment]
Was base switching removed?

**Comment by egeldenhuys** [comment]
When you click on edit you can change the base

**Pull request closed without merging**
