### PR TITLE
Ace editor

### PR DESCRIPTION
**Pull request by annamarieHelberg**
This solves issue #168 

Here is a pretty picture (and look the colour theme matches ours!)
stacks_editor

### CODE REVIEW

**Comment by FJMentz** [comment]
Looks really good... However we (me because I'm already assigned to it) definitely need to make the Preconfigured Stacks page because atm you can still click them and deploy the stack.

I will create this page tomorrow.

**Review by ghost — APPROVED** [review]
Awesome thanks. Seems easy enough to play around with as well thanks guys

**Review by FJMentz — APPROVED** [review]
Very Pretty! 10/10

**Review by CDuPlooy — APPROVED** [review]
Tis not my fault, we should have used vue and rust.

I am angry at you all.

**Review by egeldenhuys — CHANGES_REQUESTED** [review]
Editor looks great! Thank you.

To Do:
- [ ] Integrate editor (i.e submit the contents when the submit button is clicked)

**Comment by FJMentz** [comment]
This should now also solve #187 . :D

**Review by egeldenhuys — APPROVED** [review]
Looks good

**Pull request merged**
