### PR TITLE
Service list update

### PR DESCRIPTION
**Pull request by annamarieHelberg**
This updates the service list view with a ngx-datatable

### CODE REVIEW

**Comment by FJMentz** [comment]
Should clicking on a row after already clicked on one select both or unselect the currently selected one? ATM it selects both

**Comment by annamarieHelberg** [comment]
@FJMentz Yes, I intended for this demo to only have 1 selected row at a time. For demo 5 we can look into expanding it.

**Review by FJMentz — CHANGES_REQUESTED** [review]
Ports seem to still be objects in the table (I'm assuming this is due to there being a possibility for multiple ports associated with one service) 

@egeldenhuys any comments on a possible solution like only showing the first one or maybe even omitting it from the table?

**Comment by annamarieHelberg** [comment]
The problem I run into on my system @FJMentz  is that I have a service that doesn't contain a port object which causes problems when I change that. But, I will test it with other services and update it

**Review by FJMentz — APPROVED** [review]

**Comment by egeldenhuys** [comment]
Screenshot for future reference:
screen shot 2018-07-20 at 00 24 32

**Review by egeldenhuys — APPROVED** [review]
List view works :+1:

**Pull request merged**
