### PR TITLE
Login page

### LINKED ISSUE #48: Authentication via JWT
See [this](http://www.devglan.com/spring-security/angular-jwt-authentication)

### LINKED ISSUE #58: Login Page
Should send details to backend and store auth token

### LINKED ISSUE #100: Cannot communicate with backend - no JWT to send
The backend now enforces JWT Auth, however login has not yet been implemented.

Requires:
~#29~ #85  
#58 
#48

### PR DESCRIPTION
**Pull request by egeldenhuys**
- Closes #58 
- Closes #48
- Fixes #100 

### TODO
- [x] Fix ServicesListView

### Login page
screen shot 2018-06-15 at 17 45 33

### Error message
screen shot 2018-06-15 at 17 43 54

### Form validation
screen shot 2018-06-15 at 18 31 11

----

<details><summary>Original WIP Post</summary>

So far I have a functional (i.e. no style) prototype that works with docks-api v0.0.2 (the JWT enforcing version)

It currently supports Login and Logout. It will also not display anything other than the login page unless a valid JWT is stored in local storage.

See the Changelog for more details.

**Login Page:**
screen shot 2018-06-12 at 23 01 13

**Home (authenticated) section**
screen shot 2018-06-12 at 23 04 45

### TODO
- [x] Implement design as in #58 
- [x] Fix test cases
- [x] Form validation
</details>

### CODE REVIEW

**Comment by egeldenhuys** [comment]
I broke the tests and don't know how to fix it. @CDuPlooy what did you change in the beginning to get the tests to work?

**Comment by CDuPlooy** [comment]
I was also working on this. Using AuthGuard too xD

I'll have a look quick.

**Comment by egeldenhuys** [comment]
The code works in the browser, but the tests are most likely missing the required dependency injections.
I also made some structural changes by introducing intermediate modules... without updating the test files

**Comment by egeldenhuys** [comment]
screen shot 2018-06-15 at 17 45 33

screen shot 2018-06-15 at 17 43 54

**Comment by egeldenhuys** [comment]
Validation errors when clicking `Login`
screen shot 2018-06-15 at 18 31 11

**Comment by egeldenhuys** [comment]
@FJMentz Do we have .svg versions of the Docks logo?

**Comment by FJMentz** [comment]
@egeldenhuys So far no, but I can ask for one, sure it won't be a problem!

**Comment by egeldenhuys** [comment]
If the originals were created as SVG then it could be useful in the future, however scaling the logo down was no problem so the current files will work.

**Comment by egeldenhuys** [comment]
PR is ready for review.

Some things I am unsure about:
- Is the HTML and CSS correct? The result looks correct at least
- Lazy loading

**Review by CDuPlooy — APPROVED** [review]

**Review by FJMentz — APPROVED** [review]

**Comment by egeldenhuys** [comment]
I broke the operations button on the services list view. I will fix this after 19 June

**Review by ghost — APPROVED** [review]

**Pull request merged**
