### PR TITLE
Create volumes

### PR DESCRIPTION
**Pull request by ghost**
Add a new layout for the navbar as well as the volume component. 
The volumes view component looks as follows, a table with driver and name information displayed for each volume. The Search bar does work. 

image

Create volume navigates you to this page 
image
Where the user can set the name of the volume and the driver. The user can also add an unlimited number of driver options and labels achieved using reactive forms see below.
image
To remove a driver option or label the user can click the trash icon located to the right of value in the image above. 
Naturally the form has some validation. 
image

Once the user has successfully created a new volume they are taken back to the volume view component and they can see the new volume, There is an alert message to say the volume has been created. 
image
If the user tries to create a garbage volume a generic error message is displayed, the API does not send through enough information to display why it went wrong so there wasn't much I could think of doing to display a more specific error message, let me know if you know how to access network errors displayed in browser. 
image

### CODE REVIEW

**Review by egeldenhuys — APPROVED** [review]
Thanks for the well formatted Pull Request!

>  let me know if you know how to access network errors displayed in browser.

The Volumes Service will need to be modified.

The layout look good. Is it possible to indicate that an operation is taking place after clicking Create Volume?

Some interesting code for converting options and labels, but I can't think of a more elegant method.

**Comment by ghost** [comment]
> The layout look good. Is it possible to indicate that an operation is taking place after clicking Create Volume?

Sounds like a good idea. I'm not sure I fully understand how creating a volume works for now (Once it has been created is it immediately added to the swarm or does some back end operations need to happen? if so is it possible to pull the status of those operations?).

**Comment by egeldenhuys** [comment]
When the function to create a volume returns, it has either been created, or an error occurred - The frontend will wait for something to finish on the backend

**Review by FJMentz — APPROVED** [review]
Looks really good!

**Review by annamarieHelberg — APPROVED** [review]
Nice! Can I maybe ask that the same layout and pages be used for the other pages? This is amazing

**Pull request merged**
