### PR TITLE
AllYourBaseAreBelongToMe

### PR DESCRIPTION
**Pull request by CDuPlooy**
This is a cheat code.

### CODE REVIEW

**Review by FJMentz — APPROVED** [review]
No u

**Review by devosray — APPROVED** [review]
`rip`

**Review by FJMentz — APPROVED** [review]
How is this possible?

@FJMentz  I have no idea :(

**Review by egeldenhuys — CHANGES_REQUESTED** [review]
I will review now.

**Review by annamarieHelberg — COMMENTED** [review]
I don't like that the Travis builds are failing. Also, why are we removing these lines?

**Comment by CDuPlooy** [comment]
I deleted all the files because we are trying to merge the orphan branch into develop ^-^ Emphasis on trying

**Comment by Jason-vh** [comment]
The entire of Compiax is sitting here trying to work out what this pull request is doing

**Comment by egeldenhuys** [comment]
This PR will be replaced by another one, but doing the merge properly

**Comment by egeldenhuys** [comment]
https://github.com/TripleParity/docks-ui/pull/61

**Pull request closed without merging**
