### PR TITLE
(Refactor) The new structure for docks-ui

### LINKED ISSUE #124: Revert Home Module
As discussed in #121 the Home Module can be removed and replaced with something similar to the following in the `AppComponent`

(Not tested)
```html
<app-user-bar [hidden]="!isLoggedIn"></app-user-bar>
<div class="container-fluid page-container">
  <div class="row">

    <div class="col-md-2 col-xs-1" [hidden]="!isLoggedIn">
      <app-navbar></app-navbar>
    </div>

    <div class="col-md-10 col-xs-11" [hidden]="!isLoggedIn">
      <router-outlet></router-outlet>
    </div>
 
    <!-- To get rid of the col-md-10 class used when the user is logged in -->
    <router-outlet [hidden]="isLoggedIn"></router-outlet>

  </div>
</div>
```

### PR DESCRIPTION
**Pull request by annamarieHelberg**
This addresses #121 . This closes #124 . 

I removed the index.ts files because that caused circular dependencies. The graph page has been deleted and is now the home page. Thus, the home page will have performance graphs displayed. I had to degrade the angular cli to version 1.7.2 as version 1.7.4 caused some issues and it was the only way to solve them. I added module.ts and routing-module.ts to all the files as this is needed for the lazy loading (if I'm correct). I haven't looked into the lazy loading that much and the pagenotfound component is not 100% integrated. 

But, this will be enough to allow everyone to push to the branch without (hopefully any) problems.

Also, you will need to compile with `ng serve -aot`.

### CODE REVIEW

**Comment by egeldenhuys** [comment]
Thank you for the work! The directory structure looks good :+1: 

I will give a thorough review tomorrow.

For interest sake here are the dependency graphs generated by [Compodoc](https://github.com/compodoc/compodoc):
**Before**
before
**After**
after

**Comment by CDuPlooy** [comment]
Thank you for all the work

**Comment by egeldenhuys** [comment]
Note that `"@angular/cli": "^1.7.2"` will match versions `1.7.x`. `"@angular/cli": "~1.7.2",` will match only `1.7.2`

TODO:
- [x] Clean up imports - @egeldenhuys
- [x] Enable lazy loading - @egeldenhuys
- [x] Fix Login page no longer being in centre @annamarieHelberg
- [x] Fix `ng serve` if possible - @egeldenhuys
- [x] Fix Travis tests (In progress) - @egeldenhuys
- [x] Fix services list view @annamarieHelberg

**Comment by egeldenhuys** [comment]
Results in `refactor-lazy-loading` branch:
```
$ ng build --prod --build-optimizer --named-chunks

chunk {common} common.8f414dd1859e670efa55.chunk.js (common) 18.9 kB  [rendered]
chunk {containers.module} containers.module.60651fa5f04bd827e38e.chunk.js () 1.88 kB  [rendered]
chunk {home.module} home.module.3cd759a707b2d8678957.chunk.js () 504 kB  [rendered]
chunk {inline} inline.e5d47d5afc4d8788561c.bundle.js (inline) 1.81 kB [entry] [rendered]
chunk {login.module} login.module.9a1eab659887b6239d0f.chunk.js () 10.9 kB  [rendered]
chunk {main} main.a018f2b61a59348c17b3.bundle.js (main) 855 kB [initial] [rendered]
chunk {network.module} network.module.a6c538b56fc34ef9d075.chunk.js () 3.75 kB  [rendered]
chunk {pagenotfound.module} pagenotfound.module.203e0fef94f327a4c44c.chunk.js () 3.23 kB  [rendered]
chunk {polyfills} polyfills.a530f918dd3c19a2b35d.bundle.js (polyfills) 59.8 kB [initial] [rendered]
chunk {refresh.module} refresh.module.3c40b8401299c4c0049a.chunk.js () 1.6 kB  [rendered]
chunk {services.module} services.module.91748e254d070caa853d.chunk.js () 47.9 kB  [rendered]
chunk {styles} styles.1659069a10c03d06b604.bundle.css (styles) 215 kB [initial] [rendered]
chunk {tasks.module} tasks.module.8a8b6e68091d6e9b5354.chunk.js () 35.5 kB  [rendered]
chunk {user-management.module} user-management.module.10d59309664008871d5c.chunk.js () 200 kB  [rendered]
chunk {volumes.module} volumes.module.db5f1521cdf99ed41e7b.chunk.js () 31.2 kB  [rendered]
```

The vendor bundle is 855 KB, which is an improvement

**Comment by egeldenhuys** [comment]
Dependency graph from `refactor-lazy-loading`. I will merge my branch into this one after confirming with @annamarieHelberg 

**Before**
after

**After**
dependencies svg

**Comment by annamarieHelberg** [comment]
@egeldenhuys Thank you so much! This is great work. It looks very good. I will fix the last things that need to be done so we can get this branch merged.

Edit: I forgot to mention you can merge the branches.

**Comment by egeldenhuys** [comment]
My branch has been merged into this one, but is not showing in github.com due to the recent [GitHub service outages](https://status.github.com/messages)

I will try pushing another commit to this branch

**Comment by CDuPlooy** [comment]
Looks great

**Comment by egeldenhuys** [comment]
## Changelog
### Added
- [prettier](https://github.com/prettier/prettier) code formatter. Use with `npm run prettier` (closes #112)
- All pages are now lazy loaded, hence all pages are now Modules that import components

### Changed
- HomeModule is now the landing page for when logged in and no longer imports everything else (closes #124) 
- Directory structure has been refactored (closes #121)

**Review by ghost — APPROVED** [review]
Looks excellent thanks for all the hard work

**Review by CDuPlooy — APPROVED** [review]

**Review by FJMentz — APPROVED** [review]

**Pull request merged**
