### PR TITLE
Webhooks ui

### PR DESCRIPTION
**Pull request by CDuPlooy**
Thank you @annamarieHelberg and @Paulo-W for helping with this at the last minute.

This PR is complimentary to https://github.com/TripleParity/docks-api/pull/87

webhooks_ui
server

Note; The webhook is triggered multiple times because I've subscribed to ALL the docker events.

### CODE REVIEW

**Review by devosray — DISMISSED** [review]
This is great, it works as intended!

Few concerns:
-  No functionality to edit webhooks or retrieve their javascript after creating them.
-  The webhooks are not persistent

While these are critical components of the webhooks system, I assume they have been left out due to time constraints. I'm OK with merging without them but we have to implement those at the minimum before the final demo.

Minor issues:
- No link to help documentation. What is the `json` object being passed into the function? Without access to the server output, how can I view what it will return?

Pedantic issues that should be fixed for today's demo:
- The buttons at the bottom are sticking to the bottom of the page. Padding would be appreciated
image

Other than that, I like it :+1:

**Comment by devosray** [comment]
@CDuPlooy Could you maybe write a simple webhook that notifies Slack when a node goes down / up for today's demo?

**Comment by egeldenhuys** [comment]
```
(json) => { return {text: 'Node ' + json.Actor.Attributes.name + ' is ' + json.Actor.Attributes['state.new']}}
```

**Comment by egeldenhuys** [comment]
Hidden feature: you can delete all webhooks by sending invalid modifier code. This crashes express and docker picks up the pieces for us.

**Comment by CDuPlooy** [comment]
Sorry I wasn't checking this, we could try to add persistence  for the next demo, I don't feel comfortable with the db code :( :-1: 

@devosray  I am going to dismiss your review because I want to see what happens, but seriously though, I'll address some of these concerns before the next demo.

**Pull request merged**
