### PR TITLE
Task list view #37

### PR DESCRIPTION
**Pull request by FJMentz**
This contains the implementation of the task-service, task-model and the list-view for the tasks.

Please leave comments bellow.

### CODE REVIEW

**Comment by CDuPlooy** [comment]
I'll solve these conflicts tomorrow morning.

Thank you all ^-^

**Comment by egeldenhuys** [comment]
The Dockerfile no longer builds the app:
```
Step 6/10 : RUN npm run-script build 
---> Running in 38362a69e907 
ERR! missing script: build 
the command '/bin/sh -c npm run-script build' returned a non-zero code: 1
```

**Comment by FJMentz** [comment]
@CDuPlooy, Will you please look into this? :)

**Comment by egeldenhuys** [comment]
> @CDuPlooy, Will you please look into this? :)
@FJMentz, looking at it now

**Comment by FJMentz** [comment]
@egeldenhuys, Does this case pass in the current develop branch?

**Comment by egeldenhuys** [comment]
I implemented the fix for building in [dockerfile-fix](https://github.com/TripleParity/docks-ui/tree/dockerfile-fix). However the test cases now fail? @FJMentz , @CDuPlooy any idea why?

EDIT: I branched from the wrong commit, nevermind!

**Comment by FJMentz** [comment]
@egeldenhuys , You branched out of a old version which had that problem. This has been fixed in in the task-list-view-#37 branch.

Edit:
I believe after this commit: c394a26d888e9a7e11bad66fbf8453e77c79568c

Edit2:
Just saw that your comment was also edited voiding mine.

**Comment by egeldenhuys** [comment]
See branch [docker-build-fix](https://github.com/TripleParity/docks-ui/tree/docker-build-fix). If acceptable, you can cherry-pick the commits

**Comment by FJMentz** [comment]
Merged changes. Everything should be fine and working again. 👍

**Comment by egeldenhuys** [comment]
So I am on `http://127.0.0.1:4200/`, how do I see the task list?

**Comment by FJMentz** [comment]
Sorry was away from my pc, To see the task list say: http://127.0.0.1:4200/listTasks

Will add the link to the navbar.

**Comment by egeldenhuys** [comment]
Deployed using

UI:
```
sudo docker run --rm -it -p 4200:80 tripleparity/docks-ui:task-list-view-fix-_37
```

API:
```
sudo docker run --rm -it -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock tripleparity/docks-api:develop
```

**Comment by FJMentz** [comment]
Also just note that mock data is being used as we're not testing in a swarm yet, but performs exactly as it would in a swarm.

**Review by annamarieHelberg — APPROVED** [review]
Thank you! It was a great read

**Review by egeldenhuys — APPROVED** [review]
Looks Good

**Comment by egeldenhuys** [comment]
Note that this PR contains critical fixes (for building docker images) that should be merged into existing branches.

**Review by CDuPlooy — APPROVED** [review]

**Pull request merged**
