### PR TITLE
Basic list view for nodes

### PR DESCRIPTION
**Pull request by FJMentz**
Created a basic list view for the nodes.

Used Volumes view as a template and also changed some styling that might cause conflicts:

1. removed css in volumes view
2. externalised it to styling-aditional
3. changed the #Search css to a class and added it to volumes-view.html and nodes-view.html

Thank you :D

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Thanks for the general styling for pages like volumes but I don't think this view should be displayed as a list  #150 instead to represent a node we should display a div or card view. also see https://swarmpit.evert.io/#/nodes

**Comment by FJMentz** [comment]
@Paulo-W I want to agree with you but since we're removing the card views from the project, this will break the consistency of the site (that is currently moving away from card views), I believe?

**Review by ghost — APPROVED** [review]

**Comment by FJMentz** [comment]
For now (demo 5 = tomorrow) we'll stick with the list view but will go over to card view if we have extra time/ before project day.

**Review by CDuPlooy — APPROVED** [review]

**Comment by FJMentz** [comment]
Newest commit just adds fields to the view according to those set out in #150.

screen shot 2018-09-20 at 19 03 51

 EDIT:
Whoops: bad math

**Comment by FJMentz** [comment]
Thanks to @egeldenhuys I now understand math XD.

screen shot 2018-09-20 at 19 43 22

**Review by egeldenhuys — APPROVED** [review]
Looks very good!

**Pull request merged**
